name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair \
            -alias npatch \
            -keyalg RSA \
            -keysize 2048 \
            -validity 9999 \
            -keystore key.jks \
            -storepass npatch123 \
            -keypass npatch123 \
            -dname "CN=NPatch, O=NPatch, C=VN"

      - name: Print base64
        run: base64 -w 0 key.jks
